# Generated by Django 5.2 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionTratamiento',
            fields=[
                ('id_planificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('informetratamiento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PlanificacionTratamiento',
                'managed': False,
            },
        ),
    ]
