# Generated by Django 5.2 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFotos',
            fields=[
                ('id_reporteFotos', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ReporteFotos',
                'managed': False,
            },
        ),
    ]
