# Generated by Django 5.2 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoPlagas',
            fields=[
                ('id_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_monitoreo', models.DateField()),
                ('reporte', models.CharField(max_length=100)),
                ('observacionAnomalia', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'MonitoreoPlagas',
                'managed': False,
            },
        ),
    ]
