# Generated by Django 5.2 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSiembra',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_siembra', models.DateField()),
                ('cantidad_plantas', models.IntegerField()),
                ('tipo_planta', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('numeroLote', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'RegistroSiembra',
                'managed': False,
            },
        ),
    ]
