# Generated by Django 5.2 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionLote',
            fields=[
                ('id_gestion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gestion', models.DateField()),
                ('estado_lote', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'GestionLote',
                'managed': False,
            },
        ),
    ]
