# Generated by Django 5.2 on 2025-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPlagas',
            fields=[
                ('id_api', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePlanta', models.CharField(max_length=100)),
                ('nombreCientificoPlanta', models.CharField(max_length=100)),
                ('enfermedadPlanta', models.CharField(max_length=100)),
                ('nombreCientificoEnfermedad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ApiPlagas',
                'managed': False,
            },
        ),
    ]
